#!/bin/bash
# Security Assessment Audit Verification Script
# Generated by SPAI Swarm Security Agent
# Run this script to manually verify high-severity findings

set -e

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
OUTPUT_DIR="security_audit_$TIMESTAMP"
mkdir -p "$OUTPUT_DIR"

echo "═══════════════════════════════════════════════════════════════"
echo "   SPAI Security Audit Verification Script"
echo "   Output Directory: $OUTPUT_DIR"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# ─────────────────────────────────────────────────────────────────────────
# NETWORK CONNECTIONS AUDIT
# ─────────────────────────────────────────────────────────────────────────
echo "[1/6] Capturing network connections..."
{
    echo "=== LISTENING PORTS ==="
    ss -tulnp 2>/dev/null || netstat -tulnp 2>/dev/null || echo "ss/netstat not available"
    echo ""
    echo "=== ESTABLISHED CONNECTIONS ==="  
    ss -tupn state established 2>/dev/null || netstat -tupn 2>/dev/null | grep ESTABLISHED || echo "No established connections"
    echo ""
    echo "=== PROCESS NETWORK ACTIVITY (lsof) ==="
    lsof -i -n -P 2>/dev/null | head -50 || echo "lsof not available or no network activity"
} > "$OUTPUT_DIR/network_connections.txt"
echo "   → Saved to $OUTPUT_DIR/network_connections.txt"

# ─────────────────────────────────────────────────────────────────────────
# PROCESS LISTING AUDIT
# ─────────────────────────────────────────────────────────────────────────
echo "[2/6] Capturing process listing..."
{
    echo "=== ALL PROCESSES (ps aux) ==="
    ps aux --sort=-%cpu | head -50
    echo ""
    echo "=== PROCESS TREE ==="
    pstree -pa 2>/dev/null | head -100 || ps auxf | head -100
    echo ""
    echo "=== HIGH CPU PROCESSES (>5%) ==="
    ps aux --sort=-%cpu | awk 'NR==1 || $3>5'
    echo ""
    echo "=== HIGH MEMORY PROCESSES (>5%) ==="
    ps aux --sort=-%mem | awk 'NR==1 || $4>5'
} > "$OUTPUT_DIR/process_listing.txt"
echo "   → Saved to $OUTPUT_DIR/process_listing.txt"

# ─────────────────────────────────────────────────────────────────────────
# ROOTKIT DETECTION AUDIT
# ─────────────────────────────────────────────────────────────────────────
echo "[3/6] Running rootkit detection..."
{
    echo "=== CHKROOTKIT SCAN ==="
    if command -v chkrootkit &> /dev/null; then
        sudo chkrootkit 2>&1 || echo "chkrootkit scan completed with warnings"
    else
        echo "chkrootkit not installed. Install with: sudo apt install chkrootkit"
    fi
    echo ""
    echo "=== RKHUNTER SCAN ==="
    if command -v rkhunter &> /dev/null; then
        sudo rkhunter --check --skip-keypress --report-warnings-only 2>&1 || echo "rkhunter scan completed with warnings"
    else
        echo "rkhunter not installed. Install with: sudo apt install rkhunter"
    fi
} > "$OUTPUT_DIR/rootkit_scan.txt"
echo "   → Saved to $OUTPUT_DIR/rootkit_scan.txt"

# ─────────────────────────────────────────────────────────────────────────
# SYSTEM HARDENING AUDIT (LYNIS)
# ─────────────────────────────────────────────────────────────────────────
echo "[4/6] Running system hardening audit..."
{
    echo "=== LYNIS AUDIT ==="
    if command -v lynis &> /dev/null; then
        sudo lynis audit system --quick --no-colors 2>&1 | head -500

        echo ""
        echo "=== LYNIS WARNINGS ==="
        sudo lynis show warnings 2>/dev/null || echo "No warnings available"
        
        echo ""
        echo "=== LYNIS SUGGESTIONS ==="
        sudo lynis show suggestions 2>/dev/null | head -30 || echo "No suggestions available"
    else
        echo "lynis not installed. Install with: sudo apt install lynis"
    fi
} > "$OUTPUT_DIR/lynis_audit.txt"
echo "   → Saved to $OUTPUT_DIR/lynis_audit.txt"

# ─────────────────────────────────────────────────────────────────────────
# SUSPICIOUS ACTIVITY DETECTION
# ─────────────────────────────────────────────────────────────────────────
echo "[5/6] Checking for suspicious activity..."
{
    echo "=== SUID/SGID FILES ==="
    find /usr /bin /sbin -perm -4000 -o -perm -2000 2>/dev/null | head -30
    echo ""
    echo "=== WORLD-WRITABLE FILES IN /etc ==="
    find /etc -type f -perm -002 2>/dev/null | head -20
    echo ""
    echo "=== RECENT FILE MODIFICATIONS IN /bin /sbin ==="
    find /bin /sbin -type f -mtime -7 2>/dev/null | head -20
    echo ""
    echo "=== HIDDEN FILES IN /tmp ==="
    find /tmp -name ".*" -type f 2>/dev/null | head -20
    echo ""
    echo "=== UNUSUAL CRON JOBS ==="
    cat /etc/crontab 2>/dev/null
    ls -la /etc/cron.d/ 2>/dev/null
    echo ""
    echo "=== LOADED KERNEL MODULES ==="
    lsmod | head -30
    echo ""
    echo "=== FAILED LOGIN ATTEMPTS ==="
    sudo lastb 2>/dev/null | head -20 || echo "No failed logins or lastb not available"
} > "$OUTPUT_DIR/suspicious_activity.txt"
echo "   → Saved to $OUTPUT_DIR/suspicious_activity.txt"

# ─────────────────────────────────────────────────────────────────────────
# SUMMARY REPORT
# ─────────────────────────────────────────────────────────────────────────
echo "[6/6] Generating summary report..."
{
    echo "═══════════════════════════════════════════════════════════════"
    echo "   SECURITY AUDIT SUMMARY"
    echo "   Generated: $(date)"
    echo "   Hostname: $(hostname)"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "Files generated:"
    ls -la "$OUTPUT_DIR/"
    echo ""
    echo "Quick findings:"
    echo ""
    echo "Listening ports:"
    ss -tulnp 2>/dev/null | grep LISTEN | wc -l
    echo ""
    echo "Established connections:"
    ss -tupn state established 2>/dev/null | wc -l
    echo ""
    echo "Running processes:"
    ps aux | wc -l
    echo ""
    echo "Rootkit warnings (if any):"
    grep -i "infected\|warning\|suspicious" "$OUTPUT_DIR/rootkit_scan.txt" 2>/dev/null | head -10 || echo "None found"
} > "$OUTPUT_DIR/summary.txt"
echo "   → Saved to $OUTPUT_DIR/summary.txt"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "   AUDIT COMPLETE"
echo "   All results saved to: $OUTPUT_DIR/"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Review files:"
echo "  cat $OUTPUT_DIR/network_connections.txt"
echo "  cat $OUTPUT_DIR/process_listing.txt"
echo "  cat $OUTPUT_DIR/rootkit_scan.txt"
echo "  cat $OUTPUT_DIR/lynis_audit.txt"
echo "  cat $OUTPUT_DIR/suspicious_activity.txt"
echo "  cat $OUTPUT_DIR/summary.txt"
